#!/usr/bin/env bash

export CONTECO_LABEL="ksql_server.sasl - Conteco "
export CONTECO_DESCRIPTION="Confluent KSQL Server image, using SASL authentication."

export CONTECO_TYPE="ksql_server"
export CONTECO_NAME="sasl"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="external.ksql_server:5.4.0"
export CONTECO_BUILD="image-base"
